## 4.1 상장법인 목록 추출하기

실제 엑셀 내용이 html로 되어있기 때문에, read_html로 해서 읽어야 한다고 함

### 4.1.2 read_html() 함수로 read

In [15]:
import pandas as pd

krx_list = pd.read_html("C:/python/0500.quant/02.data/상장법인목록.xls")
krx_list

[             회사명    종목코드                   업종  \
 0            리파인  377450           기타 정보 서비스업
 1     지앤비에스엔지니어링  382800        특수 목적용 기계 제조업
 2       아이패밀리에스씨  114840          기타 화학제품 제조업
 3              젬  248020        전구 및 조명장치 제조업
 4         차백신연구소  261780      자연과학 및 공학 연구개발업
 ...          ...     ...                  ...
 2467      CJ대한통운     120            도로 화물 운송업
 2468       메리츠화재      60                  보험업
 2469          경방      50               종합 소매업
 2470       유수홀딩스     700  회사 본부 및 경영 컨설팅 서비스업
 2471    한진중공업홀딩스    3480    연료용 가스 제조 및 배관공급업

                                                    주요제품         상장일  결산월  \
 0                                                  권리조사  2021-10-29  12월
 1                                    스크러버, 트랩, 백연제거장치 등  2021-10-29  12월
 2         색조화장품 브랜드 `롬앤(Rom&nd)', IT기반 웨딩서비스 브랜드 `아이웨딩`  2021-10-28  12월
 3                                              LED 조명장치  2021-10-22  12월
 4                                          백신 및 면역증강제 등  2021-10-22  12월
 ...                                                 ...         ...  ...
 2467  Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...  1956-07-02  12월
 2468                                   손해보험(화재,해상,운송보험)  1956-07-02  12월
 2469          섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입  1956-03-03  12월
 2470                                               지주사업  1956-03-03  12월
 2471                                               지주회사  1956-03-03  12월

           대표자명                          홈페이지     지역
 0          이창섭       http://www.refine.co.kr  서울특별시
 1          박상순        http://www.gnbseng.com    경기도
 2     김태욱, 김성현      http://www.ifamily.co.kr  서울특별시
 3          박춘하         http://www.zamled.com   충청북도
 4          염정선     http://www.chavaccine.com    경기도
 ...        ...                           ...    ...
 2467       강신호    http://www.cjlogistics.com  서울특별시
 2468       김용범     http://www.meritzfire.com  서울특별시
 2469    김준, 김담    http://www.kyungbang.co.kr  서울특별시
 2470       송영규  http://www.eusu-holdings.com  서울특별시
 2471  조남호, 조원국  http://www.hhic-holdings.com    경기도

 [2472 rows x 9 columns]]

> 조금은 이상하게 나온다...

In [16]:
"""제대로 해서 뽑으려면 인덱스에 [0]을 넣어주면 된다"""
krx_list[0]

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,리파인,377450,기타 정보 서비스업,권리조사,2021-10-29,12월,이창섭,http://www.refine.co.kr,서울특별시
1,지앤비에스엔지니어링,382800,특수 목적용 기계 제조업,"스크러버, 트랩, 백연제거장치 등",2021-10-29,12월,박상순,http://www.gnbseng.com,경기도
2,아이패밀리에스씨,114840,기타 화학제품 제조업,"색조화장품 브랜드 `롬앤(Rom&nd)', IT기반 웨딩서비스 브랜드 `아이웨딩`",2021-10-28,12월,"김태욱, 김성현",http://www.ifamily.co.kr,서울특별시
3,젬,248020,전구 및 조명장치 제조업,LED 조명장치,2021-10-22,12월,박춘하,http://www.zamled.com,충청북도
4,차백신연구소,261780,자연과학 및 공학 연구개발업,백신 및 면역증강제 등,2021-10-22,12월,염정선,http://www.chavaccine.com,경기도
...,...,...,...,...,...,...,...,...,...
2467,CJ대한통운,120,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,강신호,http://www.cjlogistics.com,서울특별시
2468,메리츠화재,60,보험업,"손해보험(화재,해상,운송보험)",1956-07-02,12월,김용범,http://www.meritzfire.com,서울특별시
2469,경방,50,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준, 김담",http://www.kyungbang.co.kr,서울특별시
2470,유수홀딩스,700,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2471,한진중공업홀딩스,3480,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,"조남호, 조원국",http://www.hhic-holdings.com,경기도

- map 함수로 보정  
위에서 볼 수 있듯, 종목코드가 앞 0이 제외되어 뽑힌다

In [17]:
krx_list[0].종목코드 = krx_list[0].종목코드.map("{:06d}".format)
krx_list[0]

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,리파인,377450,기타 정보 서비스업,권리조사,2021-10-29,12월,이창섭,http://www.refine.co.kr,서울특별시
1,지앤비에스엔지니어링,382800,특수 목적용 기계 제조업,"스크러버, 트랩, 백연제거장치 등",2021-10-29,12월,박상순,http://www.gnbseng.com,경기도
2,아이패밀리에스씨,114840,기타 화학제품 제조업,"색조화장품 브랜드 `롬앤(Rom&nd)', IT기반 웨딩서비스 브랜드 `아이웨딩`",2021-10-28,12월,"김태욱, 김성현",http://www.ifamily.co.kr,서울특별시
3,젬,248020,전구 및 조명장치 제조업,LED 조명장치,2021-10-22,12월,박춘하,http://www.zamled.com,충청북도
4,차백신연구소,261780,자연과학 및 공학 연구개발업,백신 및 면역증강제 등,2021-10-22,12월,염정선,http://www.chavaccine.com,경기도
...,...,...,...,...,...,...,...,...,...
2467,CJ대한통운,000120,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,강신호,http://www.cjlogistics.com,서울특별시
2468,메리츠화재,000060,보험업,"손해보험(화재,해상,운송보험)",1956-07-02,12월,김용범,http://www.meritzfire.com,서울특별시
2469,경방,000050,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준, 김담",http://www.kyungbang.co.kr,서울특별시
2470,유수홀딩스,000700,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2471,한진중공업홀딩스,003480,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,"조남호, 조원국",http://www.hhic-holdings.com,경기도

> 우선 map 함수는 시리즈에서 인수로 받은 함수로 값을 변경한다고 한다.  
`map(변환 함수, 순회 가능한 데이터)`
  
> {:06d}의 의미는 6자리 숫자 형식으로 뽑되, 앞을 0으로 채우라는 의미라고 한다.

- url로 읽어들이기  
url로 바로 읽어들일 수 있다고 한다!

In [27]:
"""
대신 krx 홈페이지에서 엑셀 다운로드의 경로를 추출해줘야 한다.
"""
krx_list2 = pd.read_html("https://kind.krx.co.kr/corpgeneral/corpList.do?method=download&pageIndex=1&currentPageSize=3000&comAbbrv=&beginIndex=&orderMode=3&orderStat=D&isurCd=&repIsuSrtCd=&searchCodeType=&marketType=&searchType=13&industry=&fiscalYearEnd=all&comAbbrvTmp=&location=all")[0]

In [28]:
krx_list2['종목코드'] = krx_list2['종목코드'].map('{:06d}'.format)
krx_list2

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,리파인,377450,기타 정보 서비스업,권리조사,2021-10-29,12월,이창섭,http://www.refine.co.kr,서울특별시
1,지앤비에스엔지니어링,382800,특수 목적용 기계 제조업,"스크러버, 트랩, 백연제거장치 등",2021-10-29,12월,박상순,http://www.gnbseng.com,경기도
2,아이패밀리에스씨,114840,기타 화학제품 제조업,"색조화장품 브랜드 `롬앤(Rom&nd)', IT기반 웨딩서비스 브랜드 `아이웨딩`",2021-10-28,12월,"김태욱, 김성현",http://www.ifamily.co.kr,서울특별시
3,젬,248020,전구 및 조명장치 제조업,LED 조명장치,2021-10-22,12월,박춘하,http://www.zamled.com,충청북도
4,차백신연구소,261780,자연과학 및 공학 연구개발업,백신 및 면역증강제 등,2021-10-22,12월,염정선,http://www.chavaccine.com,경기도
...,...,...,...,...,...,...,...,...,...
2467,CJ대한통운,000120,도로 화물 운송업,"Contract Logistics, 포워딩, 항만하역, 해운, 택배국제특송, SCM...",1956-07-02,12월,강신호,http://www.cjlogistics.com,서울특별시
2468,메리츠화재,000060,보험업,"손해보험(화재,해상,운송보험)",1956-07-02,12월,김용범,http://www.meritzfire.com,서울특별시
2469,경방,000050,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준, 김담",http://www.kyungbang.co.kr,서울특별시
2470,유수홀딩스,000700,회사 본부 및 경영 컨설팅 서비스업,지주사업,1956-03-03,12월,송영규,http://www.eusu-holdings.com,서울특별시
2471,한진중공업홀딩스,003480,연료용 가스 제조 및 배관공급업,지주회사,1956-03-03,12월,"조남호, 조원국",http://www.hhic-holdings.com,경기도

In [29]:
krx_list2 = krx_list2.sort_values(by = '종목코드')
krx_list2

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
2378,동화약품,000020,의약품 제조업,"의약품 제조,판매,수출입",1976-03-24,12월,유준하,http://www.dong-wha.co.kr,서울특별시
2370,KR모터스,000040,그외 기타 운송장비 제조업,"이륜차(오토바이) 제조,도매",1976-05-25,12월,노성석,http://www.krmotors.com,경상남도
2469,경방,000050,종합 소매업,"섬유류(면사,면혼방사,면직물,면혼방직물,화섬사,화섬직물) 제조,도매,수출입",1956-03-03,12월,"김준, 김담",http://www.kyungbang.co.kr,서울특별시
2468,메리츠화재,000060,보험업,"손해보험(화재,해상,운송보험)",1956-07-02,12월,김용범,http://www.meritzfire.com,서울특별시
2460,삼양홀딩스,000070,기타 금융업,"지주회사,경영자문컨설팅",1968-12-27,12월,"엄태웅, 윤재엽",http://www.samyang.com,서울특별시
...,...,...,...,...,...,...,...,...,...
325,SNK,950180,소프트웨어 개발 및 공급업,"IP 라이센스, 콘솔, 모바일 게임",2019-05-07,07월,"갈지휘, 마츠바라 켄지",http://www.snk-corp.co.jp,일본
164,미투젠,950190,소프트웨어 개발 및 공급업,"캐주얼게임, 소셜카지노게임",2020-08-18,12월,린즈웨이/라우호밍,http://www.me2zen.com,홍콩
186,소마젠,950200,"그외 기타 전문, 과학 및 기술 서비스업","유전체 분석 서비스 (NGS, CES 등)",2020-07-13,12월,Ryan W. Kim (김운봉),http://psomagen.com,미국
95,프레스티지바이오파마,950210,자연과학 및 공학 연구개발업,바이오시밀러 및 항체의약품 신약,2021-02-05,06월,박소연,http://www.prestigebiopharma.com,싱가포르
81,네오이뮨텍,950220,자연과학 및 공학 연구개발업,면역항암제,2021-03-16,12월,양세환,http://neoimmunetech.co.kr,미국

## 4.2  HTML 익히기

In [1]:
%%writefile c:\python\0500.quant\html_sample.html
    <!doctype html>
    <html>
        <head>
            <title>this is title.</title>
        </head>
        <body>
            <h1>this is heading1 text</h1>
            <h2>this is heading2 text</h2>
            <h3>this is heading3 text</h3>
            <p>this is a paragraph</p>
            this is plain text<br />
            <b>this is bold text</b><br />
            <i>this is italic txt</i><br />
            <s>this is strike text</s>
            <ol>
                <li>the first ordered list item</li>
                <li>the segundo ordered list item</li>
                <li>the third ordered list item</li>
            </ol>
            <ul>
                <li>unordered list</li>
                <li>unordered list</li>
                <li>unordered list</li>
            </ul>
            <a href="https://www.python.org">visit python homepage!<br />
            <img src = "https://www.python.org/static/img/python-logo.png" /> </a>
        </body>
    </html>

Overwriting c:\python\0500.quant\html_sample.html

## 4.3 웹에서 월별 시세 구하기

### 4.3.1 네이버 금융 일별시세 분석

페이지 소스 보기를 클릭하면 일별 시세 페이지의 끝이 어디인지 알 수 있다.

## 4.4 Beautiful soup

In [3]:
!pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\users\jiho0\anaconda3\lib\site-packages (4.9.3)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in c:\users\jiho0\anaconda3\lib\site-packages (from beautifulsoup4) (2.0.1)

### 4.4.2 find_all(), find()

`find_all(['검색할 태그'][, class = '클래스 속성값'][,id = '아이디 속성값'][, limit = 찾을 개수])`  
  
`find(['검색할 태그'][, class = '클래스 속성값'][, id = '아이디 속성값'])`

### 4.4.3 맨 뒤 페이지 숫자 구하기

In [27]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
import requests

#우선 분석하고자 하는 url을 긁어옴
url = "https://finance.naver.com/item/sise_day.naver?code=000720&page=2"

with urlopen(url) as doc : 
    html = BeautifulSoup(doc, 'lxml')
    pgrr = html.find('td', class_= 'pdRR')
    print(pgrr.a['href'])

AttributeError: 'NoneType' object has no attribute 'a'

In [32]:
url = 'https://finance.naver.com/item/sise_day.nhn?code=000720&page=2'
url_html = requests.get('https://finance.naver.com/item/sise_day.naver?code=000720&page=1')

In [33]:
url_html.text

'\n<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n<head>\n<meta http-equiv="Content-Type" content="text/html; charset=euc-kr">\n<title>네이버 :: 세상의 모든 지식, 네이버</title>\n\n<style type="text/css">\n.error_content * {margin:0;padding:0;}\n.error_content img{border:none;}\n.error_content em {font-style:normal;}\n.error_content {width:410px; margin:80px auto 0; padding:57px 0 0 0; font-size:12px; font-family:"나눔고딕", "NanumGothic", "돋움", Dotum, AppleGothic, Sans-serif; text-align:left; line-height:14px; background:url(https://ssl.pstatic.net/static/common/error/090610/bg_thumb.gif) no-repeat center top; white-space:nowrap;}\n.error_content p{margin:0;}\n.error_content .error_desc {margin-bottom:21px; overflow:hidden; text-align:center;}\n.error_content .error_desc2 {margin-bottom:11px; padding-bottom:7px; color:#888; line-height:18px; border-bottom:1px solid #eee;}\n.error_content .error_desc3 {clear:both; color:#888;}\n.error_content .error_desc3 a {color:#004790; text-decoration:underline;}\n.error_content .error_list_type {clear:both; float:left; width:410px; _width:428px; margin:0 0 18px 0; *margin:0 0 7px 0; padding-bottom:13px; font-size:13px; color:#000; line-height:18px; border-bottom:1px solid #eee;}\n.error_content .error_list_type dt {float:left; width:60px; _width /**/:70px; padding-left:10px; background:url(https://ssl.pstatic.net/static/common/error/090610/bg_dot.gif) no-repeat 2px 8px;}\n.error_content .error_list_type dd {float:left; width:336px; _width /**/:340px; padding:0 0 0 4px;}\n.error_content .error_list_type dd span {color:#339900; letter-spacing:0;}\n.error_content .error_list_type dd a{color:#339900;}\n.error_content p.btn{margin:29px 0 100px; text-align:center;}\n</style>\n</head>\n<!-- ERROR -->\n<body>\n<div class="error_content">\n\t<p class="error_desc"><img src="https://ssl.pstatic.net/static/common/error/090610/txt_desc5.gif" width="319" height="30" alt="페이지를 찾을 수 없습니다."></p>\n\t<p class="error_desc2">방문하시려는 페이지의 주소가 잘못 입력되었거나,<br>\n\t\t페이지의 주소가 변경 혹은 삭제되어 요청하신 페이지를 찾을 수 없습니다.<br>\n\t\t입력하신 주소가 정확한지 다시 한번 확인해 주시기 바랍니다.\n\t</p>\n\t<p class="error_desc3">관련 문의사항은 <a href="https://help.naver.com/" target="_blank">고객센터</a>에 알려주시면 친절히 안내해드리겠습니다. 감사합니다.</p>\n\t<p class="btn">\n\t\t<a href="javascript:history.back()"><img src="https://ssl.pstatic.net/static/common/error/090610/btn_prevpage.gif" width="115" height="35" alt="이전 페이지로"></a>\n\t\t<a href="https://finance.naver.com"><img src="https://ssl.pstatic.net/static/nfinance/btn_home.gif" width="115" height="35" alt="금융홈으로"></a>\n\t</p>\n</div>\n</body>\n</html>\n'

In [29]:
BeautifulSoup(url_html, 'lxml')

TypeError: object of type 'Response' has no len()